server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stationery_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
<<<<<<< HEAD
    password: sharayu2123
=======
<<<<<<< HEAD
    password: Swati@1012
=======
    password: Shravani@123
>>>>>>> b41701ed275464c5071a51973b52548d6f152a60
>>>>>>> a8163695820187bd7b5dea38a10fa6a2dca9169a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sharayumohite45@gmail.com # 👈 Put YOUR Gmail address
    password: zgud yhba dlvj zghr   # 👈 Put your Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
